    # ==========================
# Configuraci�n de Spring Boot
# ==========================
# Configuracin de Spring Boot
# ==========================
spring.application.name=gymetraMembership
spring.config.import=optional:file:.env.development[.properties]
server.port=${GYMETRA_MEMBERSHIP_PORT:8081}
server.address=0.0.0.0

# ==========================
# Configuracin de la Base de Datos
# ==========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gymdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# Configuracin de JPA/Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================
# Logging SQL (opcional)
# ==========================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicExtractor=TRACE
logging.level.org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl=WARN

# ==========================
# Stripe
# ==========================
stripe.secret.key=${STRIPE_SECRET_KEY:}

# ==========================
# Configuracin de Email
# ==========================
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:}
spring.mail.password=${SPRING_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ==========================
# Configuración Unificada de Aplicación
# ==========================
app.security.cognito.issuer=${COGNITO_ISSUER_URI:}
app.security.cognito.client-id=${COGNITO_CLIENT_ID:}

# Configuración estándar de Spring Security para JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=${COGNITO_ISSUER_URI:}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${COGNITO_JWKS_URI:}
