spring.application.name=GYMETRA

server.port=${GYMETRA_QR_PORT:8090}
server.address=0.0.0.0
# ==========================
# Configuración de la Base de Datos
# ==========================
spring.datasource.url=jdbc:postgresql://localhost:5432/gymdb
spring.datasource.username=postgres
spring.datasource.password=1234567890
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# Configuración de JPA/Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================
# Logging SQL (opcional)
# ==========================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicExtractor=TRACE
logging.level.org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl=WARN

# ==========================
# Configuración Unificada de Aplicación
# ==========================
app.security.cognito.issuer=https://cognito-idp.us-east-2.amazonaws.com/us-east-2_ckSy7zPAt
app.security.cognito.client-id=3gnvfec5v6tfp32u634mq645ll

# Configuración estándar de Spring Security para JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-2.amazonaws.com/us-east-2_ckSy7zPAt
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cognito-idp.us-east-2.amazonaws.com/us-east-2_ckSy7zPAt/.well-known/jwks.json

# URLs de Microservicios
app.services.membership-url=http://localhost:8081/api

# ExerciseDB RapidAPI Config
rapidapi.exercise.key=81c075eaa5msheca677f5a5e80ecp198243jsnea5dad57b50b
rapidapi.exercise.host=exercisedb.p.rapidapi.com

# Spoonacular API Config (Nutrición)
# Obtén tu llave en spoonacular.com/food-api
spoonacular.api.key=f5a2894b90mshd15678eb1789c66p1a0212jsn56789abcde
spoonacular.api.url=https://api.spoonacular.com

