spring.application.name=GYMETRA

server.port=8090
server.address=0.0.0.0
# ==========================
# Configuración de la Base de Datos
# ==========================
spring.datasource.url=jdbc:postgresql://localhost:5000/gymdb_dev
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# Configuración de JPA/Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================
# Logging SQL (opcional)
# ==========================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicExtractor=TRACE
logging.level.org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl=WARN

# ==========================
# Configuración Unificada de Aplicación
# ==========================
app.security.cognito.issuer=https://cognito-idp.us-east-2.amazonaws.com/us-east-2_ckSy7zPAt
app.security.cognito.client-id=3gnvfec5v6tfp32u634mq645ll

# Configuración estándar de Spring Security para JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-2.amazonaws.com/us-east-2_ckSy7zPAt
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cognito-idp.us-east-2.amazonaws.com/us-east-2_ckSy7zPAt/.well-known/jwks.json

# URLs de Microservicios
app.services.membership-url=http://localhost:8081/api

