spring.application.name=GYMETRA
spring.config.import=optional:file:.env.development[.properties]

server.port=${GYMETRA_QR_PORT:8090}
server.address=0.0.0.0
# ==========================
# Configuración de la Base de Datos
# ==========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gymdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# Configuración de JPA/Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================
# Logging SQL (opcional)
# ==========================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicExtractor=TRACE
logging.level.org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl=WARN

# ==========================
# Configuración Unificada de Aplicación
# ==========================
app.security.cognito.issuer=${COGNITO_ISSUER_URI:}
app.security.cognito.client-id=${COGNITO_CLIENT_ID:}

# Configuración estándar de Spring Security para JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=${COGNITO_ISSUER_URI:}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${COGNITO_JWKS_URI:}

# URLs de Microservicios
app.services.membership-url=http://localhost:8081/api

# ExerciseDB RapidAPI Config
rapidapi.exercise.key=${RAPIDAPI_EXERCISE_KEY:c9c5ed512fmsh0621c9ccf7914ffp11686ejsn38d31105eab6}
rapidapi.exercise.host=${RAPIDAPI_EXERCISE_HOST:exercisedb.p.rapidapi.com}

# Spoonacular API Config (Nutrición)
# Obtén tu llave en spoonacular.com/food-api
spoonacular.api.key=${SPOONACULAR_API_KEY:3a5d9c6246f941e094ef26347b6fc766}
spoonacular.api.url=https://api.spoonacular.com

